"""add_cost_fields_and_system_settings

Revision ID: 1a11ad98f25a
Revises: acebef36f95f
Create Date: 2026-08-08 13:54:13.380177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a11ad98f25a'
down_revision: Union[str, None] = 'acebef36f95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.alter_column('project_costs', 'cost_type_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='نوع هزینه',
               existing_nullable=False)
    op.alter_column('project_costs', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='مبلغ (ریال)',
               existing_nullable=False)
    op.alter_column('project_costs', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='توضیح',
               existing_nullable=True)
    op.alter_column('project_costs', 'cost_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='تاریخ هزینه',
               existing_nullable=True)
    op.add_column('project_devices', sa.Column('material_unit_cost', sa.Numeric(precision=18, scale=2), nullable=True, comment='هزینه مواد واحد — از BOM'))
    op.add_column('project_devices', sa.Column('labor_unit_cost', sa.Numeric(precision=18, scale=2), nullable=True, comment='هزینه کار واحد — از Routing'))
    op.add_column('project_devices', sa.Column('direct_unit_cost', sa.Numeric(precision=18, scale=2), nullable=True, comment='هزینه مستقیم = مواد + کار'))
    op.add_column('project_devices', sa.Column('overhead_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='درصد سربار — snapshot از SystemSettings'))
    op.add_column('project_devices', sa.Column('overhead_unit_cost', sa.Numeric(precision=18, scale=2), nullable=True, comment='هزینه سربار واحد'))
    op.add_column('project_devices', sa.Column('estimated_unit_cost', sa.Numeric(precision=18, scale=2), nullable=True, comment='هزینه تمام\u200cشده واحد = مستقیم + سربار'))
    op.add_column('project_devices', sa.Column('markup_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='درصد markup — snapshot از SystemSettings'))
    op.add_column('project_devices', sa.Column('suggested_sale_unit_price', sa.Numeric(precision=18, scale=2), nullable=True, comment='قیمت پیشنهادی فروش واحد'))
    op.add_column('project_devices', sa.Column('bom_revision_no', sa.Integer(), nullable=True, comment='شماره revision BOM در زمان محاسبه'))
    op.add_column('project_devices', sa.Column('routing_revision_no', sa.Integer(), nullable=True, comment='شماره revision Routing در زمان محاسبه'))
    op.add_column('project_devices', sa.Column('cost_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('project_devices', sa.Column('cost_calculated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_devices', sa.Column('cost_is_locked', sa.Boolean(), server_default='false', nullable=False, comment='قفل بعد از in_production — محاسبه مجدد ممنوع'))
    op.alter_column('project_devices', 'device_template_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='قالب دستگاه',
               existing_nullable=False)
    op.alter_column('project_devices', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='تعداد',
               existing_nullable=False)
    op.alter_column('project_devices', 'unit_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='قیمت فروش نهایی واحد — تعیین شده توسط کاربر',
               existing_comment='قیمت واحد (ریال)',
               existing_nullable=True)
    op.alter_column('project_devices', 'bom_header_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='BOM مورد استفاده',
               existing_nullable=True)
    op.alter_column('project_devices', 'routing_header_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Routing مورد استفاده',
               existing_nullable=True)
    op.alter_column('project_devices', 'production_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='وضعیت: pending / in_progress / completed / on_hold',
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='نام پروژه',
               existing_nullable=False)
    op.alter_column('projects', 'contract_no',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='شماره قرارداد',
               existing_nullable=True)
    op.alter_column('projects', 'customer_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='مشتری',
               existing_nullable=False)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='وضعیت: draft / confirmed / in_production / delivered / cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('projects', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='اولویت: low / normal / high / urgent',
               existing_nullable=True)
    op.alter_column('projects', 'start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='تاریخ شروع',
               existing_nullable=True)
    op.alter_column('projects', 'delivery_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='تاریخ تحویل',
               existing_nullable=True)
    op.alter_column('projects', 'actual_delivery_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='تاریخ تحویل واقعی',
               existing_nullable=True)
    op.alter_column('projects', 'contract_value',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='ارزش قرارداد (ریال)',
               existing_nullable=True)
    op.alter_column('projects', 'currency',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='واحد پول: IRR / USD / EUR',
               existing_nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='توضیحات',
               existing_nullable=True)
    op.alter_column('projects', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='یادداشت\u200cهای داخلی',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'notes',
               existing_type=sa.TEXT(),
               comment='یادداشت\u200cهای داخلی',
               existing_nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               comment='توضیحات',
               existing_nullable=True)
    op.alter_column('projects', 'currency',
               existing_type=sa.VARCHAR(length=10),
               comment='واحد پول: IRR / USD / EUR',
               existing_nullable=True)
    op.alter_column('projects', 'contract_value',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='ارزش قرارداد (ریال)',
               existing_nullable=True)
    op.alter_column('projects', 'actual_delivery_date',
               existing_type=sa.DATE(),
               comment='تاریخ تحویل واقعی',
               existing_nullable=True)
    op.alter_column('projects', 'delivery_date',
               existing_type=sa.DATE(),
               comment='تاریخ تحویل',
               existing_nullable=True)
    op.alter_column('projects', 'start_date',
               existing_type=sa.DATE(),
               comment='تاریخ شروع',
               existing_nullable=True)
    op.alter_column('projects', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment='اولویت: low / normal / high / urgent',
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='وضعیت: draft / confirmed / in_production / delivered / cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('projects', 'customer_id',
               existing_type=sa.INTEGER(),
               comment='مشتری',
               existing_nullable=False)
    op.alter_column('projects', 'contract_no',
               existing_type=sa.VARCHAR(length=50),
               comment='شماره قرارداد',
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='نام پروژه',
               existing_nullable=False)
    op.alter_column('project_devices', 'production_status',
               existing_type=sa.VARCHAR(length=20),
               comment='وضعیت: pending / in_progress / completed / on_hold',
               existing_nullable=True)
    op.alter_column('project_devices', 'routing_header_id',
               existing_type=sa.INTEGER(),
               comment='Routing مورد استفاده',
               existing_nullable=True)
    op.alter_column('project_devices', 'bom_header_id',
               existing_type=sa.INTEGER(),
               comment='BOM مورد استفاده',
               existing_nullable=True)
    op.alter_column('project_devices', 'unit_price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='قیمت واحد (ریال)',
               existing_comment='قیمت فروش نهایی واحد — تعیین شده توسط کاربر',
               existing_nullable=True)
    op.alter_column('project_devices', 'quantity',
               existing_type=sa.INTEGER(),
               comment='تعداد',
               existing_nullable=False)
    op.alter_column('project_devices', 'device_template_id',
               existing_type=sa.INTEGER(),
               comment='قالب دستگاه',
               existing_nullable=False)
    op.drop_column('project_devices', 'cost_is_locked')
    op.drop_column('project_devices', 'cost_calculated_at')
    op.drop_column('project_devices', 'cost_version')
    op.drop_column('project_devices', 'routing_revision_no')
    op.drop_column('project_devices', 'bom_revision_no')
    op.drop_column('project_devices', 'suggested_sale_unit_price')
    op.drop_column('project_devices', 'markup_percent')
    op.drop_column('project_devices', 'estimated_unit_cost')
    op.drop_column('project_devices', 'overhead_unit_cost')
    op.drop_column('project_devices', 'overhead_percent')
    op.drop_column('project_devices', 'direct_unit_cost')
    op.drop_column('project_devices', 'labor_unit_cost')
    op.drop_column('project_devices', 'material_unit_cost')
    op.alter_column('project_costs', 'cost_date',
               existing_type=sa.DATE(),
               comment='تاریخ هزینه',
               existing_nullable=True)
    op.alter_column('project_costs', 'description',
               existing_type=sa.TEXT(),
               comment='توضیح',
               existing_nullable=True)
    op.alter_column('project_costs', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='مبلغ (ریال)',
               existing_nullable=False)
    op.alter_column('project_costs', 'cost_type_id',
               existing_type=sa.INTEGER(),
               comment='نوع هزینه',
               existing_nullable=False)
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
