"""add_departments_work_centers_machines

Revision ID: 1e1ea3fa16d4
Revises: eae79df48e59
Create Date: 2026-08-04 12:11:35.363925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1ea3fa16d4'
down_revision: Union[str, None] = 'eae79df48e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='کد دپارتمان - مثل DEP-001'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='نام دپارتمان'),
    sa.Column('department_type', sa.String(length=50), nullable=True, comment='کد Lookup نوع دپارتمان'),
    sa.Column('manager_name', sa.String(length=100), nullable=True, comment='نام مسئول/مدیر دپارتمان'),
    sa.Column('location', sa.String(length=150), nullable=True, comment='محل/موقعیت دپارتمان در کارگاه'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='تلفن داخلی'),
    sa.Column('notes', sa.Text(), nullable=True, comment='یادداشت\u200cها'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='وضعیت'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_index(op.f('ix_departments_status'), 'departments', ['status'], unique=False)
    op.create_table('work_centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='کد مرکز کار - مثل WC-001'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='نام مرکز کار'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='دپارتمان مربوطه'),
    sa.Column('work_center_type', sa.String(length=50), nullable=True, comment='کد Lookup نوع مرکز کار'),
    sa.Column('capacity_per_hour', sa.Numeric(precision=10, scale=2), nullable=True, comment='ظرفیت تولید در ساعت'),
    sa.Column('capacity_unit', sa.String(length=50), nullable=True, comment='واحد ظرفیت (قطعه/کیلوگرم/...)'),
    sa.Column('shift_count', sa.Integer(), server_default='1', nullable=False, comment='تعداد شیفت\u200cهای کاری'),
    sa.Column('location', sa.String(length=150), nullable=True, comment='موقعیت در کارگاه'),
    sa.Column('notes', sa.Text(), nullable=True, comment='یادداشت\u200cها'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='وضعیت'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_centers_code'), 'work_centers', ['code'], unique=True)
    op.create_index(op.f('ix_work_centers_department_id'), 'work_centers', ['department_id'], unique=False)
    op.create_index(op.f('ix_work_centers_name'), 'work_centers', ['name'], unique=False)
    op.create_index(op.f('ix_work_centers_status'), 'work_centers', ['status'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='کد ماشین - مثل MCH-001'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='نام ماشین'),
    sa.Column('machine_type', sa.String(length=50), nullable=True, comment='کد Lookup نوع ماشین'),
    sa.Column('brand', sa.String(length=100), nullable=True, comment='برند/سازنده'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='مدل'),
    sa.Column('serial_number', sa.String(length=100), nullable=True, comment='شماره سریال'),
    sa.Column('manufacture_year', sa.Integer(), nullable=True, comment='سال ساخت (میلادی)'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='دپارتمان'),
    sa.Column('work_center_id', sa.Integer(), nullable=True, comment='مرکز کار'),
    sa.Column('location', sa.String(length=150), nullable=True, comment='موقعیت دقیق در کارگاه'),
    sa.Column('capacity_per_hour', sa.Numeric(precision=10, scale=2), nullable=True, comment='ظرفیت تولید در ساعت'),
    sa.Column('hourly_rate', sa.Numeric(precision=18, scale=2), nullable=True, comment='نرخ ساعتی استفاده'),
    sa.Column('currency', sa.String(length=50), server_default='irr', nullable=False, comment='کد Lookup ارز'),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True, comment='تاریخ آخرین سرویس'),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True, comment='تاریخ سرویس بعدی'),
    sa.Column('maintenance_interval_days', sa.Integer(), nullable=True, comment='فاصله سرویس\u200cدهی (روز)'),
    sa.Column('technical_notes', sa.Text(), nullable=True, comment='مشخصات فنی'),
    sa.Column('notes', sa.Text(), nullable=True, comment='یادداشت\u200cها'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='وضعیت'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_code'), 'machines', ['code'], unique=True)
    op.create_index(op.f('ix_machines_department_id'), 'machines', ['department_id'], unique=False)
    op.create_index(op.f('ix_machines_name'), 'machines', ['name'], unique=False)
    op.create_index(op.f('ix_machines_status'), 'machines', ['status'], unique=False)
    op.create_index(op.f('ix_machines_work_center_id'), 'machines', ['work_center_id'], unique=False)
    op.alter_column('cost_types', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment='کد نوع هزینه - مثل COST-0001',
               existing_comment='کد هزینه - مثل COST-0001',
               existing_nullable=False)
    op.alter_column('cost_types', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='نام نوع هزینه',
               existing_comment='نام هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'category',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='کد Lookup دسته\u200cبندی هزینه',
               existing_comment='دسته\u200cبندی: مستقیم/غیرمستقیم/ثابت/متغیر',
               existing_nullable=False)
    op.alter_column('cost_types', 'cost_behavior',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='کد Lookup رفتار هزینه',
               existing_comment='رفتار هزینه: ثابت/متغیر/نیمه\u200cمتغیر/پلکانی',
               existing_nullable=False)
    op.alter_column('cost_types', 'unit',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='کد Lookup واحد هزینه',
               existing_comment='واحد هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'allocation_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment='کد Lookup روش تخصیص هزینه',
               existing_comment='روش تخصیص هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='نوع هزینه والد',
               existing_comment='هزینه والد (ساختار درختی)',
               existing_nullable=True)
    op.create_index(op.f('ix_cost_types_category'), 'cost_types', ['category'], unique=False)
    op.create_index(op.f('ix_cost_types_status'), 'cost_types', ['status'], unique=False)
    op.alter_column('customers', 'customer_type',
               existing_type=sa.VARCHAR(length=50),
               comment='کد Lookup نوع مشتری (real/legal)',
               existing_comment='نوع مشتری',
               existing_nullable=False,
               existing_server_default=sa.text("'legal'::character varying"))
    op.alter_column('customers', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='وضعیت مشتری',
               existing_comment='وضعیت',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_customers_customer_type'), 'customers', ['customer_type'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.alter_column('manufacturing_operations', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment='کد عملیات - مثل OP-0001',
               existing_nullable=False)
    op.alter_column('manufacturing_operations', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment='نام عملیات',
               existing_nullable=False)
    op.alter_column('manufacturing_operations', 'operation_type',
               existing_type=sa.VARCHAR(length=50),
               comment='کد Lookup نوع عملیات',
               existing_nullable=False)
    op.alter_column('manufacturing_operations', 'description',
               existing_type=sa.TEXT(),
               comment='توضیحات',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'is_outsourced',
               existing_type=sa.BOOLEAN(),
               comment='برون\u200cسپاری می\u200cشود؟',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('manufacturing_operations', 'requires_qc',
               existing_type=sa.BOOLEAN(),
               comment='نیاز به کنترل کیفیت دارد؟',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('manufacturing_operations', 'requires_machine',
               existing_type=sa.BOOLEAN(),
               comment='نیاز به ماشین دارد؟ (اگر خیر، عملیات دستی است)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('manufacturing_operations', 'is_bottleneck',
               existing_type=sa.BOOLEAN(),
               comment='گلوگاه تولید است؟',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('manufacturing_operations', 'setup_time',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='زمان راه\u200cاندازی',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'setup_time_unit',
               existing_type=sa.VARCHAR(length=50),
               comment='کد Lookup واحد زمان راه\u200cاندازی',
               existing_nullable=False,
               existing_server_default=sa.text("'minute'::character varying"))
    op.alter_column('manufacturing_operations', 'cycle_time',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='زمان تولید یک قطعه',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'cycle_time_unit',
               existing_type=sa.VARCHAR(length=50),
               comment='کد Lookup واحد زمان تولید',
               existing_nullable=False,
               existing_server_default=sa.text("'minute'::character varying"))
    op.alter_column('manufacturing_operations', 'capacity_per_hour',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='ظرفیت تولید در ساعت',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'default_operator_count',
               existing_type=sa.INTEGER(),
               comment='تعداد اپراتور پیش\u200cفرض',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('manufacturing_operations', 'efficiency_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='راندمان (%)',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'oee_target',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='هدف OEE (%)',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'hourly_rate',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='نرخ ساعتی',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'currency',
               existing_type=sa.VARCHAR(length=50),
               comment='کد Lookup ارز',
               existing_nullable=False,
               existing_server_default=sa.text("'irr'::character varying"))
    op.alter_column('manufacturing_operations', 'skill_level',
               existing_type=sa.VARCHAR(length=50),
               comment='کد Lookup سطح مهارت',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'required_skills_description',
               existing_type=sa.TEXT(),
               comment='توضیح مهارت\u200cهای لازم',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'required_tools',
               existing_type=sa.TEXT(),
               comment='ابزار لازم',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'safety_notes',
               existing_type=sa.TEXT(),
               comment='نکات ایمنی',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'notes',
               existing_type=sa.TEXT(),
               comment='یادداشت\u200cها',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='وضعیت',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index('ix_mfg_ops_code', table_name='manufacturing_operations')
    op.drop_index('ix_mfg_ops_name', table_name='manufacturing_operations')
    op.drop_index('ix_mfg_ops_operation_type', table_name='manufacturing_operations')
    op.drop_index('ix_mfg_ops_status', table_name='manufacturing_operations')
    op.create_index(op.f('ix_manufacturing_operations_code'), 'manufacturing_operations', ['code'], unique=True)
    op.create_index(op.f('ix_manufacturing_operations_name'), 'manufacturing_operations', ['name'], unique=False)
    op.create_index(op.f('ix_manufacturing_operations_operation_type'), 'manufacturing_operations', ['operation_type'], unique=False)
    op.create_index(op.f('ix_manufacturing_operations_status'), 'manufacturing_operations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manufacturing_operations_status'), table_name='manufacturing_operations')
    op.drop_index(op.f('ix_manufacturing_operations_operation_type'), table_name='manufacturing_operations')
    op.drop_index(op.f('ix_manufacturing_operations_name'), table_name='manufacturing_operations')
    op.drop_index(op.f('ix_manufacturing_operations_code'), table_name='manufacturing_operations')
    op.create_index('ix_mfg_ops_status', 'manufacturing_operations', ['status'], unique=False)
    op.create_index('ix_mfg_ops_operation_type', 'manufacturing_operations', ['operation_type'], unique=False)
    op.create_index('ix_mfg_ops_name', 'manufacturing_operations', ['name'], unique=False)
    op.create_index('ix_mfg_ops_code', 'manufacturing_operations', ['code'], unique=True)
    op.alter_column('manufacturing_operations', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='وضعیت',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('manufacturing_operations', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='یادداشت\u200cها',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'safety_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='نکات ایمنی',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'required_tools',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='ابزار لازم',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'required_skills_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='توضیح مهارت\u200cهای لازم',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'skill_level',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='کد Lookup سطح مهارت',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'currency',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='کد Lookup ارز',
               existing_nullable=False,
               existing_server_default=sa.text("'irr'::character varying"))
    op.alter_column('manufacturing_operations', 'hourly_rate',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='نرخ ساعتی',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'oee_target',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='هدف OEE (%)',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'efficiency_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='راندمان (%)',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'default_operator_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='تعداد اپراتور پیش\u200cفرض',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('manufacturing_operations', 'capacity_per_hour',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='ظرفیت تولید در ساعت',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'cycle_time_unit',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='کد Lookup واحد زمان تولید',
               existing_nullable=False,
               existing_server_default=sa.text("'minute'::character varying"))
    op.alter_column('manufacturing_operations', 'cycle_time',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='زمان تولید یک قطعه',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'setup_time_unit',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='کد Lookup واحد زمان راه\u200cاندازی',
               existing_nullable=False,
               existing_server_default=sa.text("'minute'::character varying"))
    op.alter_column('manufacturing_operations', 'setup_time',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='زمان راه\u200cاندازی',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'is_bottleneck',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='گلوگاه تولید است؟',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('manufacturing_operations', 'requires_machine',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='نیاز به ماشین دارد؟ (اگر خیر، عملیات دستی است)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('manufacturing_operations', 'requires_qc',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='نیاز به کنترل کیفیت دارد؟',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('manufacturing_operations', 'is_outsourced',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='برون\u200cسپاری می\u200cشود؟',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('manufacturing_operations', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='توضیحات',
               existing_nullable=True)
    op.alter_column('manufacturing_operations', 'operation_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='کد Lookup نوع عملیات',
               existing_nullable=False)
    op.alter_column('manufacturing_operations', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='نام عملیات',
               existing_nullable=False)
    op.alter_column('manufacturing_operations', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='کد عملیات - مثل OP-0001',
               existing_nullable=False)
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_type'), table_name='customers')
    op.alter_column('customers', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='وضعیت',
               existing_comment='وضعیت مشتری',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('customers', 'customer_type',
               existing_type=sa.VARCHAR(length=50),
               comment='نوع مشتری',
               existing_comment='کد Lookup نوع مشتری (real/legal)',
               existing_nullable=False,
               existing_server_default=sa.text("'legal'::character varying"))
    op.drop_index(op.f('ix_cost_types_status'), table_name='cost_types')
    op.drop_index(op.f('ix_cost_types_category'), table_name='cost_types')
    op.alter_column('cost_types', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='هزینه والد (ساختار درختی)',
               existing_comment='نوع هزینه والد',
               existing_nullable=True)
    op.alter_column('cost_types', 'allocation_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'direct'::character varying"),
               comment='روش تخصیص هزینه',
               existing_comment='کد Lookup روش تخصیص هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'unit',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'rial'::character varying"),
               comment='واحد هزینه',
               existing_comment='کد Lookup واحد هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'cost_behavior',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'variable'::character varying"),
               comment='رفتار هزینه: ثابت/متغیر/نیمه\u200cمتغیر/پلکانی',
               existing_comment='کد Lookup رفتار هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'category',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'direct'::character varying"),
               comment='دسته\u200cبندی: مستقیم/غیرمستقیم/ثابت/متغیر',
               existing_comment='کد Lookup دسته\u200cبندی هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='نام هزینه',
               existing_comment='نام نوع هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment='کد هزینه - مثل COST-0001',
               existing_comment='کد نوع هزینه - مثل COST-0001',
               existing_nullable=False)
    op.drop_index(op.f('ix_machines_work_center_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_status'), table_name='machines')
    op.drop_index(op.f('ix_machines_name'), table_name='machines')
    op.drop_index(op.f('ix_machines_department_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_code'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_work_centers_status'), table_name='work_centers')
    op.drop_index(op.f('ix_work_centers_name'), table_name='work_centers')
    op.drop_index(op.f('ix_work_centers_department_id'), table_name='work_centers')
    op.drop_index(op.f('ix_work_centers_code'), table_name='work_centers')
    op.drop_table('work_centers')
    op.drop_index(op.f('ix_departments_status'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
