"""add_specializations_to_suppliers

Revision ID: 5a87964fd42b
Revises: 62ba041b1cb3
Create Date: 2026-08-04 09:45:41.742551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a87964fd42b'
down_revision: Union[str, None] = '62ba041b1cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('specializations', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'specializations')
    # ### end Alembic commands ###
