"""add_lookups_table

Revision ID: 62ba041b1cb3
Revises: 60450842d0e5
Create Date: 2026-08-04 08:59:20.084660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62ba041b1cb3'
down_revision: Union[str, None] = '60450842d0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='دسته: supplier_type, cost_category, ...'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='کد یکتا در دسته: manufacturer, direct, ...'),
    sa.Column('label_fa', sa.String(length=150), nullable=False, comment='لیبل فارسی'),
    sa.Column('label_en', sa.String(length=150), nullable=True, comment='لیبل انگلیسی (اختیاری)'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='والد (برای زیرشاخه\u200cها)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='ترتیب نمایش در لیست'),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False, comment='اگر True: کاربر نمی\u200cتواند حذف کند'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='فعال/غیرفعال'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='داده\u200cهای اضافی: رنگ، آیکون، تنظیمات...'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['lookups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'code', name='uq_lookup_category_code')
    )
    op.create_index('ix_lookup_category_active', 'lookups', ['category', 'is_active'], unique=False)
    op.create_index('ix_lookup_parent', 'lookups', ['parent_id'], unique=False)
    op.create_index(op.f('ix_lookups_category'), 'lookups', ['category'], unique=False)
    op.alter_column('cost_types', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment='کد هزینه - مثل COST-0001',
               existing_nullable=False)
    op.alter_column('cost_types', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='نام هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'category',
               existing_type=postgresql.ENUM('direct', 'indirect', 'fixed', 'variable', name='costcategory'),
               comment='دسته\u200cبندی: مستقیم/غیرمستقیم/ثابت/متغیر',
               existing_nullable=False)
    op.alter_column('cost_types', 'cost_behavior',
               existing_type=postgresql.ENUM('fixed', 'variable', 'semi_variable', 'step', name='costbehavior'),
               comment='رفتار هزینه: ثابت/متغیر/نیمه\u200cمتغیر/پلکانی',
               existing_nullable=False)
    op.alter_column('cost_types', 'unit',
               existing_type=postgresql.ENUM('rial', 'dollar', 'euro', 'percent', 'hour', 'unit', name='costunit'),
               comment='واحد هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'default_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='مبلغ پیش\u200cفرض',
               existing_nullable=True)
    op.alter_column('cost_types', 'allocation_method',
               existing_type=postgresql.ENUM('direct', 'machine_hour', 'labor_hour', 'production_qty', 'area', 'manual', name='allocationmethod'),
               comment='روش تخصیص هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'account_code',
               existing_type=sa.VARCHAR(length=30),
               comment='کد حسابداری',
               existing_nullable=True)
    op.alter_column('cost_types', 'taxable',
               existing_type=sa.BOOLEAN(),
               comment='مشمول مالیات',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cost_types', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='هزینه والد (ساختار درختی)',
               existing_nullable=True)
    op.alter_column('cost_types', 'description',
               existing_type=sa.TEXT(),
               comment='توضیحات',
               existing_nullable=True)
    op.alter_column('cost_types', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'archived', name='coststatus'),
               comment='وضعیت',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::coststatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cost_types', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'archived', name='coststatus'),
               comment=None,
               existing_comment='وضعیت',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::coststatus"))
    op.alter_column('cost_types', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='توضیحات',
               existing_nullable=True)
    op.alter_column('cost_types', 'parent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='هزینه والد (ساختار درختی)',
               existing_nullable=True)
    op.alter_column('cost_types', 'taxable',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='مشمول مالیات',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cost_types', 'account_code',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='کد حسابداری',
               existing_nullable=True)
    op.alter_column('cost_types', 'allocation_method',
               existing_type=postgresql.ENUM('direct', 'machine_hour', 'labor_hour', 'production_qty', 'area', 'manual', name='allocationmethod'),
               comment=None,
               existing_comment='روش تخصیص هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'default_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='مبلغ پیش\u200cفرض',
               existing_nullable=True)
    op.alter_column('cost_types', 'unit',
               existing_type=postgresql.ENUM('rial', 'dollar', 'euro', 'percent', 'hour', 'unit', name='costunit'),
               comment=None,
               existing_comment='واحد هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'cost_behavior',
               existing_type=postgresql.ENUM('fixed', 'variable', 'semi_variable', 'step', name='costbehavior'),
               comment=None,
               existing_comment='رفتار هزینه: ثابت/متغیر/نیمه\u200cمتغیر/پلکانی',
               existing_nullable=False)
    op.alter_column('cost_types', 'category',
               existing_type=postgresql.ENUM('direct', 'indirect', 'fixed', 'variable', name='costcategory'),
               comment=None,
               existing_comment='دسته\u200cبندی: مستقیم/غیرمستقیم/ثابت/متغیر',
               existing_nullable=False)
    op.alter_column('cost_types', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='نام هزینه',
               existing_nullable=False)
    op.alter_column('cost_types', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='کد هزینه - مثل COST-0001',
               existing_nullable=False)
    op.drop_index(op.f('ix_lookups_category'), table_name='lookups')
    op.drop_index('ix_lookup_parent', table_name='lookups')
    op.drop_index('ix_lookup_category_active', table_name='lookups')
    op.drop_table('lookups')
    # ### end Alembic commands ###
