"""add_item_cost_fields

Revision ID: 92b6c735568f
Revises: d170ee3f9cfa
Create Date: 2026-08-04 20:52:14.749173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92b6c735568f'
down_revision: Union[str, None] = 'd170ee3f9cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='فعال/غیرفعال',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('device_templates', 'approved_by_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='تأییدکننده',
               existing_nullable=True)
    op.alter_column('device_templates', 'approved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='تاریخ تأیید',
               existing_nullable=True)
    op.alter_column('device_templates', 'created_by_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ایجادکننده',
               existing_nullable=True)
    op.add_column('items', sa.Column('standard_cost', sa.Numeric(precision=18, scale=2), nullable=True, comment='هزینه استاندارد واحد'))
    op.add_column('items', sa.Column('currency', sa.String(length=10), nullable=True, comment='کد Lookup ارز'))
    op.alter_column('items', 'manufacturer',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=50),
               comment='کد Lookup سازنده',
               existing_comment='سازنده',
               existing_nullable=True)
    op.alter_column('items', 'material_grade',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               comment='کد Lookup گرید متریال',
               existing_comment='گرید متریال',
               existing_nullable=True)
    op.alter_column('items', 'surface_treatment',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               comment='کد Lookup نوع پوشش',
               existing_comment='نوع پوشش/آبکاری',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'surface_treatment',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               comment='نوع پوشش/آبکاری',
               existing_comment='کد Lookup نوع پوشش',
               existing_nullable=True)
    op.alter_column('items', 'material_grade',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               comment='گرید متریال',
               existing_comment='کد Lookup گرید متریال',
               existing_nullable=True)
    op.alter_column('items', 'manufacturer',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=150),
               comment='سازنده',
               existing_comment='کد Lookup سازنده',
               existing_nullable=True)
    op.drop_column('items', 'currency')
    op.drop_column('items', 'standard_cost')
    op.alter_column('device_templates', 'created_by_id',
               existing_type=sa.INTEGER(),
               comment='ایجادکننده',
               existing_nullable=True)
    op.alter_column('device_templates', 'approved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='تاریخ تأیید',
               existing_nullable=True)
    op.alter_column('device_templates', 'approved_by_id',
               existing_type=sa.INTEGER(),
               comment='تأییدکننده',
               existing_nullable=True)
    op.alter_column('device_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='فعال/غیرفعال',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
