"""add_project_tables

Revision ID: acebef36f95f
Revises: f1a2b3c4d5e6
Create Date: 2026-08-08 09:12:25.256504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acebef36f95f'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_no', sa.String(length=30), nullable=False, comment='شماره پروژه — PRJ-0001'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='نام پروژه'),
    sa.Column('contract_no', sa.String(length=50), nullable=True, comment='شماره قرارداد'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='مشتری'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='وضعیت: draft / confirmed / in_production / delivered / cancelled'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='اولویت: low / normal / high / urgent'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='تاریخ شروع'),
    sa.Column('delivery_date', sa.Date(), nullable=True, comment='تاریخ تحویل'),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True, comment='تاریخ تحویل واقعی'),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=True, comment='ارزش قرارداد (ریال)'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='واحد پول: IRR / USD / EUR'),
    sa.Column('description', sa.Text(), nullable=True, comment='توضیحات'),
    sa.Column('notes', sa.Text(), nullable=True, comment='یادداشت\u200cهای داخلی'),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_customer_id'), 'projects', ['customer_id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_no'), 'projects', ['project_no'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('project_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cost_type_id', sa.Integer(), nullable=False, comment='نوع هزینه'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='مبلغ (ریال)'),
    sa.Column('description', sa.Text(), nullable=True, comment='توضیح'),
    sa.Column('cost_date', sa.Date(), nullable=True, comment='تاریخ هزینه'),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_type_id'], ['cost_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_costs_project_id'), 'project_costs', ['project_id'], unique=False)
    op.create_table('project_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('device_template_id', sa.Integer(), nullable=False, comment='قالب دستگاه'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='تعداد'),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True, comment='قیمت واحد (ریال)'),
    sa.Column('bom_header_id', sa.Integer(), nullable=True, comment='BOM مورد استفاده'),
    sa.Column('routing_header_id', sa.Integer(), nullable=True, comment='Routing مورد استفاده'),
    sa.Column('production_status', sa.String(length=20), nullable=True, comment='وضعیت: pending / in_progress / completed / on_hold'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bom_header_id'], ['bom_headers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_template_id'], ['device_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routing_header_id'], ['routing_headers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_devices_device_template_id'), 'project_devices', ['device_template_id'], unique=False)
    op.create_index(op.f('ix_project_devices_project_id'), 'project_devices', ['project_id'], unique=False)
    op.alter_column('routing_headers', 'device_template_id',
               existing_type=sa.INTEGER(),
               comment='تعریف دستگاه',
               existing_nullable=False)
    op.alter_column('routing_headers', 'revision_no',
               existing_type=sa.INTEGER(),
               comment='شماره Revision',
               existing_nullable=False)
    op.alter_column('routing_headers', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='وضعیت: draft / approved / obsolete',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('routing_headers', 'effective_from',
               existing_type=sa.DATE(),
               comment='شروع اعتبار',
               existing_nullable=True)
    op.alter_column('routing_headers', 'effective_to',
               existing_type=sa.DATE(),
               comment='پایان اعتبار',
               existing_nullable=True)
    op.alter_column('routing_operations', 'step_no',
               existing_type=sa.INTEGER(),
               comment='شماره مرحله (10, 20, 30, ...)',
               existing_nullable=False)
    op.alter_column('routing_operations', 'operation_id',
               existing_type=sa.INTEGER(),
               comment='نوع عملیات',
               existing_nullable=False)
    op.alter_column('routing_operations', 'department_id',
               existing_type=sa.INTEGER(),
               comment='دپارتمان',
               existing_nullable=True)
    op.alter_column('routing_operations', 'work_center_id',
               existing_type=sa.INTEGER(),
               comment='مرکز کار',
               existing_nullable=True)
    op.alter_column('routing_operations', 'machine_id',
               existing_type=sa.INTEGER(),
               comment='ماشین',
               existing_nullable=True)
    op.alter_column('routing_operations', 'setup_time_min',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='زمان آماده\u200cسازی (دقیقه)',
               existing_nullable=True)
    op.alter_column('routing_operations', 'cycle_time_min',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='زمان سیکل (دقیقه)',
               existing_nullable=True)
    op.alter_column('routing_operations', 'labor_count',
               existing_type=sa.INTEGER(),
               comment='تعداد نیروی کار',
               existing_nullable=True)
    op.alter_column('routing_operations', 'hourly_rate',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment='نرخ ساعتی ماشین/نیروی کار (ریال)',
               existing_nullable=True)
    op.alter_column('routing_operations', 'is_outsourced',
               existing_type=sa.BOOLEAN(),
               comment='برون\u200cسپاری',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routing_operations', 'is_outsourced',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='برون\u200cسپاری',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('routing_operations', 'hourly_rate',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               comment=None,
               existing_comment='نرخ ساعتی ماشین/نیروی کار (ریال)',
               existing_nullable=True)
    op.alter_column('routing_operations', 'labor_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='تعداد نیروی کار',
               existing_nullable=True)
    op.alter_column('routing_operations', 'cycle_time_min',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='زمان سیکل (دقیقه)',
               existing_nullable=True)
    op.alter_column('routing_operations', 'setup_time_min',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='زمان آماده\u200cسازی (دقیقه)',
               existing_nullable=True)
    op.alter_column('routing_operations', 'machine_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ماشین',
               existing_nullable=True)
    op.alter_column('routing_operations', 'work_center_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='مرکز کار',
               existing_nullable=True)
    op.alter_column('routing_operations', 'department_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='دپارتمان',
               existing_nullable=True)
    op.alter_column('routing_operations', 'operation_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='نوع عملیات',
               existing_nullable=False)
    op.alter_column('routing_operations', 'step_no',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='شماره مرحله (10, 20, 30, ...)',
               existing_nullable=False)
    op.alter_column('routing_headers', 'effective_to',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='پایان اعتبار',
               existing_nullable=True)
    op.alter_column('routing_headers', 'effective_from',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='شروع اعتبار',
               existing_nullable=True)
    op.alter_column('routing_headers', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='وضعیت: draft / approved / obsolete',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('routing_headers', 'revision_no',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='شماره Revision',
               existing_nullable=False)
    op.alter_column('routing_headers', 'device_template_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='تعریف دستگاه',
               existing_nullable=False)
    op.drop_index(op.f('ix_project_devices_project_id'), table_name='project_devices')
    op.drop_index(op.f('ix_project_devices_device_template_id'), table_name='project_devices')
    op.drop_table('project_devices')
    op.drop_index(op.f('ix_project_costs_project_id'), table_name='project_costs')
    op.drop_table('project_costs')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_no'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_customer_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
