"""add_engineering_module

Revision ID: d170ee3f9cfa
Revises: 1e1ea3fa16d4
Create Date: 2026-08-04 19:35:03.385038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd170ee3f9cfa'
down_revision: Union[str, None] = '1e1ea3fa16d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False, comment='کد قلم - ITM-0001'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='نام قلم'),
    sa.Column('item_type', sa.String(length=50), nullable=False, comment='کد Lookup نوع قلم'),
    sa.Column('uom', sa.String(length=20), nullable=False, comment='کد Lookup واحد'),
    sa.Column('specification', sa.Text(), nullable=True, comment='مشخصات فنی'),
    sa.Column('drawing_no', sa.String(length=100), nullable=True, comment='شماره نقشه'),
    sa.Column('part_no', sa.String(length=100), nullable=True, comment='شماره قطعه داخلی'),
    sa.Column('manufacturer', sa.String(length=150), nullable=True, comment='سازنده'),
    sa.Column('manufacturer_part_no', sa.String(length=100), nullable=True, comment='شماره قطعه سازنده'),
    sa.Column('weight', sa.Numeric(precision=10, scale=4), nullable=True, comment='وزن (کیلوگرم)'),
    sa.Column('material_grade', sa.String(length=100), nullable=True, comment='گرید متریال'),
    sa.Column('surface_treatment', sa.String(length=100), nullable=True, comment='نوع پوشش/آبکاری'),
    sa.Column('notes', sa.Text(), nullable=True, comment='یادداشت\u200cها'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='وضعیت'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_code'), 'items', ['code'], unique=True)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_table('device_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False, comment='کد دستگاه - DVT-0001'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='نام دستگاه'),
    sa.Column('template_type', sa.String(length=50), nullable=True, comment='کد Lookup نوع دستگاه'),
    sa.Column('revision_no', sa.Integer(), nullable=False, comment='شماره Revision'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='وضعیت'),
    sa.Column('description', sa.Text(), nullable=True, comment='توضیحات'),
    sa.Column('technical_notes', sa.Text(), nullable=True, comment='نکات مهندسی'),
    sa.Column('default_uom', sa.String(length=20), nullable=True, comment='کد Lookup واحد'),
    sa.Column('estimated_weight', sa.Numeric(precision=10, scale=3), nullable=True, comment='وزن تقریبی (کیلوگرم)'),
    sa.Column('estimated_cycle_time', sa.Integer(), nullable=True, comment='زمان ساخت استاندارد (دقیقه)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='فعال/غیرفعال'),
    sa.Column('approved_by_id', sa.Integer(), nullable=True, comment='تأییدکننده'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='تاریخ تأیید'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='ایجادکننده'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_templates_code'), 'device_templates', ['code'], unique=True)
    op.create_index(op.f('ix_device_templates_name'), 'device_templates', ['name'], unique=False)
    op.create_index(op.f('ix_device_templates_status'), 'device_templates', ['status'], unique=False)
    op.create_table('bom_headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_template_id', sa.Integer(), nullable=False, comment='قالب دستگاه'),
    sa.Column('revision_no', sa.Integer(), nullable=False, comment='شماره Revision'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='وضعیت'),
    sa.Column('effective_from', sa.Date(), nullable=True, comment='شروع اعتبار'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='پایان اعتبار'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_template_id'], ['device_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_template_id', 'revision_no', name='uq_bom_template_revision')
    )
    op.create_index(op.f('ix_bom_headers_device_template_id'), 'bom_headers', ['device_template_id'], unique=False)
    op.create_table('bom_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bom_header_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False, comment='مقدار'),
    sa.Column('uom', sa.String(length=20), nullable=True, comment='واحد (اگه با آیتم فرق داشته باشه)'),
    sa.Column('scrap_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='درصد ضایعات'),
    sa.Column('operation_id', sa.Integer(), nullable=True, comment='عملیات مصرف'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='ترتیب نمایش'),
    sa.Column('is_optional', sa.Boolean(), server_default='false', nullable=False, comment='قطعه اختیاری'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bom_header_id'], ['bom_headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['manufacturing_operations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_lines_bom_header_id'), 'bom_lines', ['bom_header_id'], unique=False)
    op.create_index(op.f('ix_bom_lines_item_id'), 'bom_lines', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bom_lines_item_id'), table_name='bom_lines')
    op.drop_index(op.f('ix_bom_lines_bom_header_id'), table_name='bom_lines')
    op.drop_table('bom_lines')
    op.drop_index(op.f('ix_bom_headers_device_template_id'), table_name='bom_headers')
    op.drop_table('bom_headers')
    op.drop_index(op.f('ix_device_templates_status'), table_name='device_templates')
    op.drop_index(op.f('ix_device_templates_name'), table_name='device_templates')
    op.drop_index(op.f('ix_device_templates_code'), table_name='device_templates')
    op.drop_table('device_templates')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_code'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
