"""add_customer_extra_fields

Revision ID: da0813c04d3e
Revises: 8e15ae0827f0
Create Date: 2026-08-05 21:07:58.705973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0813c04d3e'
down_revision: Union[str, None] = '8e15ae0827f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('code', sa.String(length=30), nullable=True, comment='کد مشتری - CUS-0001'))
    op.add_column('customers', sa.Column('tier', sa.String(length=20), server_default='b', nullable=True, comment='کد Lookup سطح مشتری (a/b/c)'))
    op.add_column('customers', sa.Column('cooperation_start', sa.Date(), nullable=True, comment='تاریخ شروع همکاری'))
    op.add_column('customers', sa.Column('contact_position', sa.String(length=50), nullable=True, comment='سمت رابط'))
    op.add_column('customers', sa.Column('website', sa.String(length=200), nullable=True, comment='وب\u200cسایت'))
    op.add_column('customers', sa.Column('province', sa.String(length=50), nullable=True, comment='استان'))
    op.add_column('customers', sa.Column('city', sa.String(length=50), nullable=True, comment='شهر'))
    op.add_column('customers', sa.Column('payment_terms', sa.String(length=50), nullable=True, comment='کد Lookup شرایط پرداخت'))
    op.add_column('customers', sa.Column('currency', sa.String(length=10), server_default='irr', nullable=True, comment='کد Lookup ارز معاملات'))
    op.add_column('customers', sa.Column('credit_days', sa.Integer(), nullable=True, comment='مدت تسویه (روز)'))
    op.add_column('customers', sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True, comment='سقف اعتبار مشتری (به ریال)'))
    op.add_column('customers', sa.Column('description', sa.Text(), nullable=True, comment='توضیحات مالی'))
    op.alter_column('customers', 'national_id',
               existing_type=sa.VARCHAR(length=20),
               comment='شناسه ملی/کد اقتصادی',
               existing_comment='شناسه ملی',
               existing_nullable=True)
    op.alter_column('customers', 'notes',
               existing_type=sa.TEXT(),
               comment='یادداشت\u200cها',
               existing_comment='توضیحات',
               existing_nullable=True)
    op.alter_column('customers', 'mobile',
               existing_type=sa.VARCHAR(length=20),
               comment='موبایل شرکت',
               existing_comment='موبایل',
               existing_nullable=True)
    op.create_index(op.f('ix_customers_code'), 'customers', ['code'], unique=True)
    op.drop_column('customers', 'contact_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('contact_title', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='سمت رابط'))
    op.drop_index(op.f('ix_customers_code'), table_name='customers')
    op.alter_column('customers', 'mobile',
               existing_type=sa.VARCHAR(length=20),
               comment='موبایل',
               existing_comment='موبایل شرکت',
               existing_nullable=True)
    op.alter_column('customers', 'notes',
               existing_type=sa.TEXT(),
               comment='توضیحات',
               existing_comment='یادداشت\u200cها',
               existing_nullable=True)
    op.alter_column('customers', 'national_id',
               existing_type=sa.VARCHAR(length=20),
               comment='شناسه ملی',
               existing_comment='شناسه ملی/کد اقتصادی',
               existing_nullable=True)
    op.drop_column('customers', 'description')
    op.drop_column('customers', 'credit_limit')
    op.drop_column('customers', 'credit_days')
    op.drop_column('customers', 'currency')
    op.drop_column('customers', 'payment_terms')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'province')
    op.drop_column('customers', 'website')
    op.drop_column('customers', 'contact_position')
    op.drop_column('customers', 'cooperation_start')
    op.drop_column('customers', 'tier')
    op.drop_column('customers', 'code')
    # ### end Alembic commands ###
